import type { Candidate, Job } from './types';

export const SAMPLE_JOB: Omit<Job, 'id' | 'created_at'> = {
  title: 'Senior Full-Stack Engineer',
  description:
    'We are hiring a Senior Full-Stack Engineer to build scalable web applications. You will work across the stack using React, TypeScript, and Node.js, design REST and GraphQL APIs, and deploy on AWS with Docker and Kubernetes. Experience with PostgreSQL, CI/CD pipelines, and microservices architecture is essential. You should be comfortable owning features end-to-end and mentoring junior engineers.',
  required_skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'PostgreSQL', 'Docker', 'GraphQL'],
  min_experience_years: 5,
};

const baseCandidate = {
  job_id: '',
  email: null,
  phone: null,
  raw_text: null,
  education: [],
  experience: [],
  projects: [],
  certifications: [],
  experience_match_text: null,
  education_match_text: null,
  error_message: null,
  created_at: new Date().toISOString(),
};

export const SAMPLE_CANDIDATES: Omit<Candidate, 'id' | 'job_id' | 'created_at'>[] = [
  {
    ...baseCandidate,
    name: 'Rahul Kumar',
    file_name: 'Rahul_Kumar_Resume.pdf',
    skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'PostgreSQL', 'Docker', 'GraphQL', 'Kubernetes', 'Python'],
    match_score: 9.2,
    skills_match_pct: 100,
    experience_match_pct: 100,
    education_match_pct: 100,
    project_match_pct: 86,
    semantic_match_pct: 92,
    matching_skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'PostgreSQL', 'Docker', 'GraphQL'],
    missing_skills: [],
    strengths: [
      'Strong technical fit with 7 of 7 required skills present.',
      '8 years of hands-on professional experience.',
      'Advanced degree in Computer Science from IIT Bombay.',
      '5 documented projects demonstrating applied skills.',
    ],
    experience_match_text: '8 years experience exceeds the 5 year minimum.',
    education_match_text: "Advanced degree in M.Tech Computer Science from IIT Bombay.",
    recommendation: 'SHORTLIST',
    justification:
      'Rahul Kumar is being evaluated for the Senior Full-Stack Engineer role. Excellent technical alignment — 7 of 7 required skills are present. Experience requirements are comfortably met. Educational background is a strong match. Overall, this candidate is recommended for shortlisting based on a strong hybrid match.',
    status: 'ready',
  },
  {
    ...baseCandidate,
    name: 'Priya Sharma',
    file_name: 'Priya_Sharma_Resume.pdf',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'GraphQL', 'Docker', 'Tailwind CSS', 'Redux'],
    match_score: 8.7,
    skills_match_pct: 86,
    experience_match_pct: 80,
    education_match_pct: 85,
    project_match_pct: 75,
    semantic_match_pct: 88,
    matching_skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'GraphQL', 'Docker'],
    missing_skills: ['AWS'],
    strengths: [
      'Solid skill coverage with 6 required skills matched.',
      '6 years of relevant work experience.',
      "Bachelor's degree in Computer Science from Delhi University.",
      '4 documented projects demonstrating applied skills.',
    ],
    experience_match_text: '6 years experience exceeds the 5 year minimum.',
    education_match_text: "Bachelor's degree in B.Tech Computer Science from Delhi University.",
    recommendation: 'SHORTLIST',
    justification:
      'Priya Sharma is being evaluated for the Senior Full-Stack Engineer role. Strong technical alignment — 6 of 7 required skills matched. Missing skills include AWS. Experience requirements are comfortably met. Educational background is a strong match. Overall, this candidate is recommended for shortlisting based on a strong hybrid match.',
    status: 'ready',
  },
  {
    ...baseCandidate,
    name: 'Arjun Reddy',
    file_name: 'Arjun_Reddy_Resume.pdf',
    skills: ['React', 'JavaScript', 'Node.js', 'Express', 'MongoDB', 'Docker'],
    match_score: 7.9,
    skills_match_pct: 57,
    experience_match_pct: 60,
    education_match_pct: 85,
    project_match_pct: 50,
    semantic_match_pct: 72,
    matching_skills: ['React', 'Node.js', 'Docker'],
    missing_skills: ['TypeScript', 'AWS', 'PostgreSQL', 'GraphQL'],
    strengths: [
      'Moderate technical alignment with 3 of 7 required skills matched.',
      '4 years of relevant work experience.',
      "Bachelor's degree in Information Technology from BITS Pilani.",
    ],
    experience_match_text: '4 years experience is below the 5 year minimum.',
    education_match_text: "Bachelor's degree in B.E. Information Technology from BITS Pilani.",
    recommendation: 'REVIEW',
    justification:
      'Arjun Reddy is being evaluated for the Senior Full-Stack Engineer role. Moderate technical alignment — 3 of 7 required skills matched. Missing skills include TypeScript, AWS, PostgreSQL, GraphQL. Experience is partially aligned with the role requirements. This candidate warrants a manual review before proceeding.',
    status: 'ready',
  },
  {
    ...baseCandidate,
    name: 'Sneha Patel',
    file_name: 'Sneha_Patel_Resume.pdf',
    skills: ['JavaScript', 'HTML', 'CSS', 'Vue', 'Firebase', 'Python'],
    match_score: 6.4,
    skills_match_pct: 14,
    experience_match_pct: 40,
    education_match_pct: 60,
    project_match_pct: 30,
    semantic_match_pct: 55,
    matching_skills: [],
    missing_skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'PostgreSQL', 'Docker', 'GraphQL'],
    strengths: [
      '2 years of relevant work experience.',
      '2 documented projects demonstrating applied skills.',
    ],
    experience_match_text: '2 years experience is below the 5 year minimum.',
    education_match_text: 'Education history present but degree level unclear.',
    recommendation: 'REVIEW',
    justification:
      'Sneha Patel is being evaluated for the Senior Full-Stack Engineer role. Limited technical alignment — only 0 of 7 required skills found. Missing skills include React, TypeScript, Node.js, AWS, PostgreSQL, Docker, GraphQL. Experience falls short of the role expectations. This candidate warrants a manual review before proceeding.',
    status: 'ready',
  },
  {
    ...baseCandidate,
    name: 'Vikram Singh',
    file_name: 'Vikram_Singh_Resume.pdf',
    skills: ['HTML', 'CSS', 'PHP', 'MySQL'],
    match_score: 4.8,
    skills_match_pct: 14,
    experience_match_pct: 20,
    education_match_pct: 50,
    project_match_pct: 10,
    semantic_match_pct: 35,
    matching_skills: [],
    missing_skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'PostgreSQL', 'Docker', 'GraphQL'],
    strengths: ['Profile shows potential for growth in the role.'],
    experience_match_text: '1 years experience is below the 5 year minimum.',
    education_match_text: 'Education history present but degree level unclear.',
    recommendation: 'REJECT',
    justification:
      'Vikram Singh is being evaluated for the Senior Full-Stack Engineer role. Limited technical alignment — only 0 of 7 required skills found. Missing skills include React, TypeScript, Node.js, AWS, PostgreSQL, Docker, GraphQL. Experience falls short of the role expectations. This candidate does not meet the threshold for this role.',
    status: 'ready',
  },
];
